### ISSUE TITLE
[Bug] Lyrics Editor is converting the timestamp float into a whole number when it should not be doing that

### ISSUE THREAD

**Issue by shea786** [nawhas/nawhas#155]
Log in as a moderator
Click on a track
Click on the edit icon
Play the track
Click on the set timestamp button when the timestamp is not on a whole seccond

Expected
In the JSON file, the float number should be stored as the timestamp

Actual
In the JSON file, the float is getting converted to a whole number

**Comment by szainmehdi** [comment]
Closed by #157
