### ISSUE TITLE
Audio functionality on the tracks page

### ISSUE THREAD

**Issue by shea786** [nawhas/nawhas#20]
Get the audio playback functionality working on the tracks page

**Comment by szainmehdi** [comment]
### Full Player
![Full Player](https://user-images.githubusercontent.com/379169/75461694-22d79c00-5951-11ea-88bb-3e7c346c01c3.png)

### Mini Player
![Mini Player](https://user-images.githubusercontent.com/379169/75461699-24a15f80-5951-11ea-9b66-b3879db46a0a.png)

### Mobile Player
![Mobile Player](https://user-images.githubusercontent.com/379169/75461702-25d28c80-5951-11ea-9eb0-f67f834652eb.png)

**Comment by shea786** [comment]
Closes #73
