### ISSUE TITLE
[Bug] When creating a new track/Editing existing track, getting error "Cannot read property 'reciter' of undefined"

### ISSUE THREAD

**Issue by shea786** [nawhas/nawhas#310]
Tested on staging

Log into system as Moderator
Go to an album and click on add track against album
Fill out details
Click on save

Expected
Should have been redirected to the reciters page

Actual
Getting error in console, Cannot read property 'reciter' of undefined
User redirected to empty blank page
![image](https://user-images.githubusercontent.com/17195904/90182593-1c779800-ddaa-11ea-8827-f314a4cb6693.png)

Same is happening when editing track
However after editing the track, error ocurred page is displayed instead of the blank page when creating new track as per above screenshot
![image](https://user-images.githubusercontent.com/17195904/90185246-5054bc80-ddae-11ea-8b91-437e6098e7ce.png)

**Comment by szainmehdi** [comment]
Here's the issue: 
https://github.com/nawhas/nawhas/blob/2b2c1cc4c5f173778c5dfa7eb5b1f83fadf365e7/nuxt/components/edit/EditTrackDialog.vue#L277-L287
