### ISSUE TITLE
[Bug] Lyrics view is displaying the data as json instead of being rendered

### ISSUE THREAD

**Issue by shea786** [nawhas/nawhas#312]
Environment: staging

Logged in as moderator
Added a new track
Added some information to lyrics and clicked on save

Expected
Lyrics json should be rendered

Actual
json itself is being displayed
![image](https://user-images.githubusercontent.com/17195904/90183609-b724a680-ddab-11ea-9503-241d10ebb747.png)

This is happening in any case even if we use the old format or the new format.
Also if we dont enter any text but changed to non-timestamped mode
Basically once we create this json structure, and we save, json structure is being displayed instead of being rendered

Also I had converted to non-timestamped added some text and then undo'd all of my changes, however in this case also json was sent instead of sending a null value to server and therefore lyrics are being displayed in wrong format

Also the metadata for this on the albums page is showing as there is lyrics for this track even though after converting to non-timestamped mode, no lyrics itself was added. but still metadata shows as there being lyrics available for that track

**Comment by szainmehdi** [comment]
Probably here somewhere we want to pass along `format`
