### ISSUE TITLE
[Bug] When registering for a new account, 500 error is thrown

### ISSUE THREAD

**Issue by shea786** [nawhas/nawhas#315]
Environment: staging

When trying to register for a new account, 500 error is thrown

I tried with an email that does not exist in the system
Same is happening even if the email address exists

I cleared out all of my cookies/cache

Expectred
Account should be created

Actual
Account is not being created
![image](https://user-images.githubusercontent.com/17195904/90186220-be4db380-ddaf-11ea-88db-d092db63f952.png)
![image](https://user-images.githubusercontent.com/17195904/90186329-e3dabd00-ddaf-11ea-950a-d24e38debdd2.png)

**Comment by szainmehdi** [comment]
Not a launch blocker, but we should do this ASAP.
