### ISSUE TITLE
Do not show reciters, albums or tracks which do not have any data

### ISSUE THREAD

**Issue by shea786** [nawhas/nawhas#37]
We do not want to show a reciter if they do not have any albums

We do not want to show an album if it doesnt have any tracks

**Comment by szainmehdi** [comment]
I'm actually not too sure if we want to do this. 

We should probably show reciters and albums with no content, especially when we open it up for editing. I'll wait on this one for now.

**Comment by shea786** [comment]
Actually yeah you have a point, i forgot about that, but then again for the first release we are not going to have updating etc

The reason why i suggested this was because on the frontend I was getting errors because albums etc didnt exist

However i have added handling for those now so we can discuss if we actually need this

**Comment by shea786** [comment]
Closing this as no longer required
