### ISSUE TITLE
Outline to the user if the track has a lyric before going to the tracks page

### ISSUE THREAD

**Issue by shea786** [nawhas/nawhas#41]
Because we have quite a few tracks that dont have lyrics. I was thinking maybe we could identify to the user on the Reciter Profile page itself somehow on the table displaying the tracks if the track has lyrics available or not.

This would save the user going into multiple tracks looking for lyrics and finding out that there are no lyrics

**Comment by shea786** [comment]
What are your thoughts @szainmehdi

**Comment by szainmehdi** [comment]
Yes, we definitely want to do this. This was the original idea:

![image](https://user-images.githubusercontent.com/379169/75097159-6b134a80-555c-11ea-8846-9d78136ade9c.png)
