### ISSUE TITLE
[Bug] [Library V1] When removing a saved track, getting a 500 internal error

### ISSUE THREAD

**Issue by shea786** [nawhas/nawhas#427]
Environment: library-integration

Log into the system
Click on Library
Find a saved track and click on it
Click on the `favourite` icon to remove the saved track

Expected
Track should get removed from saved library

Actual
Getting 500 error
Telescope suggests that there is no payload being sent and therefore the track is not getting removed
![image](https://user-images.githubusercontent.com/17195904/91973007-6ac9e800-ed13-11ea-92fd-ba8bdfb4493a.png)

**Comment by szainmehdi** [comment]
Closed by f9f6018533052feb22e4002d7dddb92d584f92e0
