### ISSUE TITLE
[Bug] [Redirects] When changing album year, and adding a new album with the previous albums original year, its not redirecting correctly within the first few minutes

### ISSUE THREAD

**Issue by shea786** [nawhas/nawhas#457]
Environment: integration

Log into system as moderator
Go to any reciter, in this case Tejani Brothers
renamed the `Shia` album year from `2019` to `2019-20`
Went to `/reciters/tejani-brothers/albums/2019` and it redirected to `2019-20`
Added a new album with the year as `2019`
Went to  `/reciters/tejani-brothers/albums/2019`

Expected
It should take me to the `2019` album

Actual
It redirected me to `2019-20` album

I refreshed a few times and eventually it went to the `2019` album

**Comment by szainmehdi** [comment]
PR #455

**Comment by shea786** [comment]
This issue is fixed
