### ISSUE TITLE
[Bug] [Redirects] When deleting an album, getting server error, status code 500

### ISSUE THREAD

**Issue by shea786** [nawhas/nawhas#458]
Environment: Redirects Integration

Log in as moderator
Go to an album
Click on edit against album
Click on `Delete` and confirm you would like to delete

Expected
Album should delete without any issues

Actual
Album is getting deleted however API is returning with status 500
Frontend showing something went wrong page

**Comment by szainmehdi** [comment]
This was an integration environment issue, fixed in 1132a963
