### ISSUE TITLE
Explore alternatives to Algolia

### ISSUE THREAD

**Issue by szainmehdi** [nawhas/nawhas#61]
Algolia can be pretty expensive. 

**Alternatives**
- [Typesense](https://typesense.org)
- [MeilliSearch](https://docs.meilisearch.com/)

**Comment by szainmehdi** [comment]
https://typesense.org/

**Comment by jasonbosco** [comment]
👋 I work on Typesense. Let me know if I can help in any way.

**Comment by szainmehdi** [comment]
Hi @jasonbosco, thanks for reaching out! 

We actually ended up implementing Meillisearch (#61)! Happy with the results so far.

**Comment by jasonbosco** [comment]
Got it! Thank you for the update.
